services:
  - type: web
    name: video-factory
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: python main.py
    plan: free
    healthCheckPath: /ping
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: ""
      - key: PEXELS_API_KEY
        sync: false
      - key: API_KEY
        sync: false
